use_frameworks!

platform :ios, '13.0'

target 'SQLiteREST_Example' do
  pod 'SQLiteREST', :path => '../'
  pod "GCDWebServer", "~> 3.0"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
