use_frameworks!

platform :ios, '10.0'

target 'SQLiteREST_Example' do
  pod 'SQLiteREST', :path => '../'

  target 'SQLiteREST_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
